# Generated by Django 3.2.9 on 2022-02-20 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Премиум объявление', 'verbose_name_plural': 'Премиум объявления'},
        ),
    ]
