# Generated by Django 3.2.9 on 2022-02-20 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0004_alter_product_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
